
const books = [
{
    id: 1,
    name: "La mala costumbre",
    author:"Alana S. Portero",
    description: "La mala costumbre es una versión bastarda y travesti del viajedel héroe: el viaje vital de una antiheroína trans en el que yonquis,divas del pop y ángeles caídos se unen para salvarla deun mundo empeñado en aplastar sus fantasías de vivir la vidaplenamente. Narrada desde una singular y desgarradora vozen primera persona, seguimos la adolescencia de una niña sinnombre atrapada en el cuerpo de un niño, una niña que intentacomprenderse a sí misma y al mundo en el que habita, desdesu infancia en una familia de clase obrera en el barrio de SanBlas, barrido por la heroína en los ochenta, hasta las nochesde fiesta salvaje del centro de Madrid en los noventa. Al final,la hermandad y los aprendizajes de las mujeres que encuentraen el camino brujas, santas, damas de cuento serán lo quela ayude a superar la violencia que enfrenta a cada paso delcamino.La mala costumbre es una novela cruda y brutal, pero tambiénpoética y conmovedora, con reminiscencias de Almodóvar, Euforiay Las malas, en la que todos los extremos se unen paramostrarnos por qué el resentimiento y la rabia contra el sistemason completamente válidos para sobrevivir en una sociedadque no acepta a los que son diferentes. Un recorrido porel miedo, el trauma, los estragos de los recuerdos imposiblesde borrar y la importancia de las palabras que elegimos decir.",
    price: 19.00,
    stock: 10,
    images: "images/lamalacostumbre.jpg",
},
{
    id: 2,
    name: "El Power Ranger rosa",
    author:"Christo Casas",
    description: "Un joven español llega a Berlín en busca de trabajo. Por la noche pone copas en un bar marica y por el día intenta escribir la historia de su abuela, que también vivió en Alemania hace muchos años. La voz de la anciana en la grabadora lo devuelve al pueblo manchego en el que se crió de niño. Cuando eres un niño marica no te puedes defender, porque todo el pueblo lo sabe antes de que tú lo sepas. Lo mejor es escapar, no te enfrentes a ellos, le dice su abuela. Ella también escapó hace muchos años. Huía de la violencia, en diferentes circunstancias, y también como él intentaba buscarse la vida. En la distancia inmensa que separa nuestra vida sexual de la de nuestras abuelas cabe el desengaño de comprobar que, por más que intentas volver a empezar, por más tierra que pones de por medio, te vas a pasar la vida saliendo del armario de clase. Aunque, como pasa con el otro armario, ya todo el mundo sabe que eres pobre antes de que tú lo sepas.",
    price: 14.00,
    stock: 2,
    images: "images/elpowerrangerrosa.jpg",
},
{
    id: 3,
    name: "Carcoma",
    author: "Layla Martínez",
    description: "Todas las casas guardan la historia de quienes las han habitado. Las paredes de esta casa perdida en el páramo hablan de voces que surgen de debajo de las camas, de santas que se aparecen en el techo de la cocina, de desapariciones que nunca se resuelven. Los vecinos reniegan de sus dos habitantes a la luz del día, pero todos acuden a ellas cuando nadie los ve. La abuela se pasa los días hablando con las sombras que viven tras las paredes y dentro de los armarios. La nieta vuelve a la casa tras un incidente con la familia más rica del pueblo. Ahora, desenredando la historia de la casa, se han empezado a dar cuenta de que las sombras que la habitan estuvieron siempre de su lado.a mala costumbre es una versión bastarda y travesti del viajedel héroe: el viaje vital de una antiheroína trans en el que yonquis,divas del pop y ángeles caídos se unen para salvarla deun mundo empeñado en aplastar sus fantasías de vivir la vidaplenamente. Narrada desde una singular y desgarradora vozen primera persona, seguimos la adolescencia de una niña sinnombre atrapada en el cuerpo de un niño, una niña que intentacomprenderse a sí misma y al mundo en el que habita, desdesu infancia en una familia de clase obrera en el barrio de SanBlas, barrido por la heroína en los ochenta, hasta las nochesde fiesta salvaje del centro de Madrid en los noventa. Al final,la hermandad y los aprendizajes de las mujeres que encuentraen el camino brujas, santas, damas de cuento serán lo quela ayude a superar la violencia que enfrenta a cada paso delcamino.La mala costumbre es una novela cruda y brutal, pero tambiénpoética y conmovedora, con reminiscencias de Almodóvar, Euforiay Las malas, en la que todos los extremos se unen paramostrarnos por qué el resentimiento y la rabia contra el sistemason completamente válidos para sobrevivir en una sociedadque no acepta a los que son diferentes. Un recorrido porel miedo, el trauma, los estragos de los recuerdos imposiblesde borrar y la importancia de las palabras que elegimos decir.",
    price: 18.00,
    stock: 7,
    images: "images/carcoma.jpg",
},
{
    id: 4,
    name: "(h)amor amigas",
    author: "VVAA",
    description: "[La amistad] Consiste en amar a un ser humano como se querría amar atoda la humanidad».De la amistad, Simone Weil Nosotras y las autoras que participan en este volumen, hamor 9 amigas, reivindicamos y practicamos la amistad en múltiples y diversas formas. Que las amigas nos pueden salvar la vida lo gritan desde siempre los feminismos, y lo llevamos como bandera las minorías, migrantes, racializadas y el colectivo LGTBQIA+. Como bibolleras también sabemos que las amigas pueden ser amantes, o sujetos de deseo, y esta forma de amistad-amorosa puede ser vivida desde la idealización, el rechazo o la identificación absoluta. Y además nos hemos dado cuenta de que la amistad en ocasiones necesita distancia, de que hay amigas que se separan, temporalmente o para siempre, de que el duelo es también un dolor que puede llegar a formar parte de este tipo en apariencia tan universal y sin embargo absolutamente particular de relaciones. La amistad, por último, debería ser crítica y no convertirse en otro concepto susceptible de ser transformado en producto de consumo por el neoliberalismo. Como bien dice Nerea Pérez de las Heras: En momentos críticos, la verdadera tragedia es no tener amigas, y añadimos: y en momentos de gozo, también. Sobre las autoraselisa coll mujeres, voces y resistencias sara torres anna pacheco alicia valdés maría bastarós las hijas de felipe andrea momoitio rubén serrano maltita maría folguera.",
    price: 14.95,
    stock: 20,
    images: "images/amoramigas.jpg",
},
{
    id: 5,
    name: "Derecho a cita",
    author: "Roberta Marrero",
    description: "«Supongo que diré cualquier cosa que me aleje de la cárcel de mi propio corazón».Dennis Cooper La escritora, artista y poeta Roberta Marrero regresa en este segundo poemario, Derecho a cita, a un personalísimo imaginario que nos habla desde las entrañas y nos arroja al centro del deseo. Un deseo, el suyo, a veces consumado, otras solo idealizado, en ocasiones frustrado, y que la autora acompaña en esta ocasión de innumerables citas extraídas de la vasta bibliografía que conforma su universo creativo, personal y emocional. En palabras de Inés Plasencia, autora del epílogo: ¿Te imaginas una habitación con Pizarnik, Lemebel, Santa Teresa de Jesús, Marrero, Crisp, Sexton? Todas en sofás de terciopelo escuchando a Lana del Rey. [] He aquí un cadáver que no será cenizas he aquí los cuerpos de la fiesta más rabiosa del mundo. La hermana de Nan Goldin. He aquí la esclava de cualquier señor.Sobre la autoraRoberta Marrero vive y escribe en Madrid. Ha publicado novela gráfica, ensayo y poesía. Este es su segundo poemario.",
    price: 16.00,
    stock: 3,
    images: "images/derechoacita.jpg",
},
{
    id: 6,
    name: "Resistencia Bisexual",
    author: "Elisa Coll",
    description: "TUna mirada potente y sin tapujos sobre la bisexualidad y la bifobia en primera persona. La escritura de Elisa Coll recurre a la investigación y las vísceras para proponernos una aproximación a la vez personal y política a la bisexualidad como identidad en constante disidencia, más allá del deseo y en abierta resistencia a la violencia estructural. La bisexualidad se transforma así en punto de encuentro, en un lugar de celebración, en un espacio habitable.",
    price: 15.00,
    stock: 7,
    images: "images/resistenciabisexual.jpg",
},
{
    id: 7,
    name: "La seducción",
    author: "Sara Torres",
    description: "Una joven fotógrafa se pone en contacto con una escritora veinte años mayor para tomarle unos retratos mientras trabaja en su próxima novela, titulada La seducción. Tras intercambiar varios correos, la escritora la invita a pasar unos días en su casa, una pequeña masía en la costa catalana. Al llegar, nada es como esperaba, la anfitriona se muestra distante y no se deja fotografiar. Ante el rechazo, la fotógrafa tomará esas instantáneas en su mente, alimentando a la vez su ansiedad y su deseo. Esa convivencia extraña en una casa en la que todo parece dispuesto para elplacer se tensará con la aparición de Greta, una amiga de la escritora con quien parece compartir una intimidad de límites difusos.Después de convertirse en una de las grandes revelaciones de la literatura española con Lo que hay, Sara Torres vuelve con una novela sobre la distancia y la fantasía sexual, una historia sobre el poder de las imágenes en el deseo y la potencia sanadora de la dulzura.",
    price: 18.90,
    stock: 9,
    images: "images/laseduccion.jpg",
},
{
    id: 8,
    name: "Contra el capacitismo",
    author: "Itxi Guerra",
    description: "TEl sistema capacitista es aquel que discrimina, violenta y asesina a las personas discapacitadas por el hecho de serlo. Surge del sistema capitalista al concebir a las personas según su capacidad de producción de beneficios a través de su fuerza de trabajo. Este fanzine busca relacionar esta opresión con el especismo, el patriarcado y el sistema carcelario, analizando de qué forma se están reproduciendo estas violencias y cómo podemos acabar con ellas desde el anarquismo y la ternura",
    price: 5.00,
    stock: 6,
    images: "images/laluchacontraelcapacitismo.jpg",
},
{
    id: 9,
    name: "Con esta Hoz",
    author: "Samuel Merino",
    description: "TCon esta hoz es un libro que alberga varios libros en sí mismo y ofrece múltiples lecturas. Samuel Merino nos presenta un poema horizontal fragmentado por un ensayo poético. Al igual que la hoz es una herramienta para la siega de gramíneas, la escritura de Samuel se corta a sí misma y desprende sus espigas ofreciendo importantes floraciones.Este libro es un viaje hacia atrás y hacia adelante en el que se pueden recorrer varios caminos que, aunque atraviesen el mismo paisaje, siempre te sorprenderán al ofrecerte una perspectiva diferente.",
    price: 12.90,
    stock: 2,
    images: "images/conestahoz.jpg",
},
{
    id: 10,
    name: "A mordiscos la orquídea",
    author: "Joan Darós",
    description: "Cinco personajes pasan el verano alrededor de una piscina rosa. Uno de ellos no pertenece a la familia. Se trata del profesor de inglés que han contratado para no descuidar la educación de Júlia. Una niña, un profesor y tres adultos: Clara, Gisbert y Grau.Obra ganadora de la primera edición del PANQ, Premio Asterisco de Narrativa Queer.",
    price: 14.00,
    stock: 3,
    images: "images/amordiscoslaorquidea.jpg",
},
{
    id: 11,
    name: "La rebelion de las hienas",
    author: "Mer Gómez",
    description: "Un viaje autobiográfico hacia el encuentro de referentes intersex para iniciar una revolución. Los relatos de sus protagonistas nos muestran la construcción de una identidad colectiva en la búsqueda de un presente/futuro de libertad y con derechos.Castellón, 2016. Nace Lola. La actriz protagonista. Sale a escena. Y va rompiendo, poco a poco, su silencio. Viaja, en busca de referentes. La primera hermafrodita a caballo está ahí, aguardando en Barcelona. A orillas del Mediterráneo aparece otra: la Melero. Una repentina llamada la lleva a Galicia, junto a la vallista del COI. Ansiosa, emigra. Instalada en Valencia se encuentra, inesperadamente, con una chiqueta del Cabanyal. Vive sus catarsis. En Logroño, baila junto a otra de las machorras.Pierde el rumbo. Descubre una brújula intersexual situada en un punto de México. Siguiente destino: País Vasco. En el pupitre de al lado se sienta la Kollontai del siglo xxi. Desde Madrid, irrumpe con fuerza la voz de una señora bien y fetén. Mientras tanto, un ave fénix extrabinarie atraviesa el cielo gris de Bizkaia. Y, entonces, pone cara al holograma del documental No box for me.¿Qué falta? Descubrir a un notas del distrito sur de Sevilla. Volver a casa. Conversar con las dos que faltaban. Parar. En Salamanca, escribe y performa. Lola se empodera y Mer se desarmariza. Por fin, ha encontrado una familia intersex. Toca defenderse, cacarear bien alto. ¿Te unes a la rebelión de las hienas?Mer Gómez «Bicha rara. Escribo desde el cruce, soy una hiena». Autora y activista intersex. Graduada en Periodismo. Especializada en Estudios Internacionales de Paz, Conflictos y Desarrollo y en Estudios Feministas y de Género. Ha escrito y protagonizado los monólogos para microteatro La revolución de Lola y Solo apto para BICHAS RARAS, así como el corto-documental Se receta silencio. Ha publicado, además, artículos como «Soy Lola y soy Intersexual», o «La i está empezando a salir del armario» en Pikara Magazine. Desde 2020, coordina el colectivo i de Intersex junto a Laura Vila Kremer. Un espacio de sensibilización desde el que forman e informan sobre intersexualidades y diversidad corporal. Actualmente, desarrolla su tesis doctoral dentro del programa de Estudios Feministas y de Género de la Universidad del País Vasco. Su objetivo es poner en el centro las experiencias de vida intersex para generar nuevos enunciados, encarnados y situados, sobre la intersexualidad.",
    price: 16.00,
    stock: 11,
    images: "images/larebeliondelashienas.jpg",
},
{
    id: 12,
    name: "Alianzas rebeldes",
    author: "Clara Serra, Cristina Garaizábal, Laura Macaya",
    description: "Este libro es un ejercicio de libertad. Es una alianza rebelde entre distintas voces comprometidas con el valor la pluralidad y el disenso en el interior del feminismo. Frente a las falsas unidades impuestas, que siempre son excluyentes, y también contra el cinismo y la indiferencia, este proyecto asume que no hay uno sino muchos feminismos y que tenemos no solo la posibilidad de disentir con algunos de ellos sino el deber de explicar nuestras discrepancias. Las autoras y autores que participan lo hacen desde sus propias perspectivas, diferentes entre sí, pero aliadas en torno a un libro decididamente crítico que afronta los principales debates que atraviesan hoy a los feminismos y toma posición con respecto a ellos. La crítica al uso excesivo que algunos feminismos han hecho de las vías penales y de diversas formas de censura reúne a una serie de voces comprometidas contra algunas derivas dogmáticas y punitivas de ciertos discursos feministas. La defensa de perspectivas no culpabilizadoras ni moralistas en el ámbito de la sexualidad es el compromiso de una serie de textos que toman posición frente a discursos feministas centrados en el peligro sexual. La defensa de un feminismo en alianza con otros movimientos y luchas sociales -en alianza con las trabajadoras sexuales, las personas trans, las mujeres migrantes y otras tantas personas atadas a vidas precarias- aglutina a una serie de autoras que toman distancia con feminismos excluyentes. La crítica a los feminismos centrados en exclusiva en las mujeres como sujeto y la apuesta por un feminismo que nos reúna no por quiénes somos sino por las ideas y proyectos que deseamos defender en común es la idea que subyace a esta defensa rebelde de las alianzas en tiempos en los que parece tan difícil hacer política feminista más allá de la identidad.Participan del libro Clara Serra, Miriam Solà, Paloma Uría, Santiago Alba Rico, Paz Francés, Violeta Assiego, Laura Pérez, Miren Ortubay, Laura Macaya, Cristina Garaizabal, Noemí Parra, Miquel Missé, Sejo Carrascosa, Josetxu Riviere, Nuria Alabao, Mamen Briz, Siobhan Guerrero.",
    price: 17.00,
    stock: 3,
    images: "images/alianzasrebeldes.jpg",
},
{
    id: 13,
    name: "Nosotras vinimos tarde",
    author: "Elisa Coll",
    description: "Tras su reconocido ensayo Resistencia bisexual, Elisa Coll debuta en el campo de lo narrativo con Nosotras vinimos tarde, una novela valiente y rompedora en la que, a través de distintos géneros, hibrida ficción y memoria histórica, creando un caleidoscopio literario cargado de belleza, inteligencia y humor.En Nosotras vinimos tarde, la autora recoge relatos pasados sobre convivencias alternativas y, desde ahí, se mira en el espejo de toda una generación que, marcada por las falsas expectativas y la precariedad, siente que llega a todo demasiado tarde. Un relato que, desde la ternura, el ingenio y la crudeza, desgrana temas como el fracaso, la amistad, los duelos o las violencias en espacios que suponemos seguros. Con esta obra, Coll nos reta a pensar en cómo construimos los espacios a los que llamamos casa y de qué formas los habitamos para, desde ahí, llevarnos a otros lugares desde los que reimaginar el futuro.",
    price: 18.00,
    stock: 7,
    images: "images/nosotrasvinimostarde.jpg",
},
{
    id: 14,
    name: "Panza de burro",
    author: "Andrea Abreu",
    description: "T«Reconozco que al principio, cuando Panza de burro solo había crecido unos capitulitos, pensé que sería una novela sencilla y hermosa que abriría un hachazo en esa tela de invernadero que parecía ocultar un imaginario y un mundo que debían ser mostrados. Más adelante, la grandeza del libro, la inteligencia y el salvajismo de Andrea, su pulso poético y su falta total de miedo hicieron trizas la rafia, y quedó a la vista una plantación intrincada, dolorosa, inmensa, nada sencilla. Hice la primera edición en un salón de Lisboa, y creo que fue allí cuando me di cuenta de que el libro era mucho más grande de lo que imaginé. También, y esto es importante, sentí envidia. Una envidia por la imposibilidad de escribir yo algo así». Sabina Urraca.",
    price: 18.90,
    stock: 3,
    images: "images/panzadeburro.jpg",
},
{
    id: 15,
    name: "Los argonautas",
    author: "Maggue Nelson",
    description: "De una honestidad implacable, en esta memoria y a la vez ensayo, Maggie Nelson narra su singular y entrañable historia de amor con Harry Dogde, un artista transgénero, y cómo, en un contexto donde aún se debate la ley de unión civil entre homosexuales, intentan construir juntos una familia.En la tradición de intelectuales como Susan Sontag y Roland Barthes, Nelson entrelaza su propia experiencia con la teoría icónica, para explorar distintas construcciones culturales en torno a las nociones de identidad, sexualidad, género, maternidad y matrimonio.«Una de las más electrificantes escritoras norteamericanas de hoy. Fusionando lo que en otras manos podrían ser áridas teorías o confesiones sensibleras, Nelson crea un vigoroso lenguaje». Olivia Laing, The Guardian.",
    price: 22.95,
    stock: 7,
    images: "images/losargonautas.jpg",
},
{
    id: 16,
    name: "Ese de anoche",
    author: "Alejandro Simón Partal",
    description: "La antología poética de Alejandro Simón Partal, uno de los autores más relevantes del momento.Esta primera antología de la poesía de Simón Partal es una gran fiesta, una esperada rave en la arena, junto a la orilla, muy cerca del mar y de sus profundidades.Ese de anoche recoge la aventura vital de un poeta que vive de cara a la vida: las sábanas tendidas en un prado abierto, un grupo de chicos que trabajan sus cuerpos en el paseo marítimo, el perro que persigue a las palomas sin intención de atraparlas, la nieve que cae sobre el campo y que exige un caminar de otra manera son algunas de las imágenes y escenarios de esta poesía orientada al milagro cercano de la existencia, versos que no explican el mundo, sino que se empapan de él. Con un fondo enigmático y sereno, la mirada de Partal es la mezcla perfecta de sabiduría y de avidez, de trascendencia y de instinto, de silencio y de hambre.Delicada y cruda, antigua y novísima, lírica y prosaica, esta poesía nos habla del ardor del deseo, del amor que otorga sentido y ofrece desapego , de lo innecesario del acontecimiento, de cómo lo divino accede a manifestarse en el rojo de los tomates, y de la impotencia que a veces se esconde en las palabras. Mientras leemos estos poemas descarnados, conmovedores, sabemos ya que se quedarán por siempre a vivir con nosotros .Piedad Bonnet.",
    price: 18.90,
    stock: 1,
    images: "images/esedeanoche.jpg",
},
{
    id: 17,
    name: "Canto yo y la montaña baila",
    author: "Irene Solá",
    description: "Luego, Dolceta, que no puede parar de reír mientras cuenta las historias de las cuatro mujeres a las que colgaron por brujas. Sió, que tiene que criar sola a Mia e Hilari ahí arriba en Matavaques. Y las trompetas de los muertos, que, con su sombrero negro y apetitoso, anuncian la inmutabilidad del ciclo de la vida.Canto yo y la montaña baila es una novela en la que toman la palabra mujeres y hombres, fantasmas y mujeres de agua, nubes y setas, perros y corzos que habitan entre Camprodon y Prats de Molló, en los Pirineos. Una zona de alta montaña y de frontera que, más allá de la leyenda, conserva la memoria de siglos de lucha por la supervivencia, de persecuciones guiadas por la ignorancia y el fanatismo, de guerras fratricidas, pero que encarna también una belleza a la que no le hacen falta muchos adjetivos. Un terreno fértil para liberar la imaginación y el pensamiento, las ganas de hablar y de contar historias. Un lugar, quizás, para empezar de nuevo y encontrar cierta redención.",
    price: 17.90,
    stock: 3,
    images: "images/cantoyolamontañabaila.jpg",
},
{
    id: 18,
    name: "Vallesordo",
    author: "Jonathan Arribas",
    description: "Una nueva y original voz de las letras españolas, una entrañable novela sobre una infancia en un pueblo de Zamora en la década de los dos mil.Nico es un niño que vive en un pueblo de Zamora. Juega a polis y cacos con los amigos, va en bici, pasa tiempo con su perra, La Yesi, se aburre y se divierte en el colegio, le duele la barriga, odia a los mastines del pastor, que le ladran sin parar, y le gusta mucho ensayar coreos.Por las tardes, a la hora de la siesta, ve Fama, ¡a bailar! y manda ánimos a Yure, su favorita, que es de Canarias y tiene pelo de leona. Cuando aprende nuevos pasos de baile se los enseña enseguida a sus amigos, Izan y Telma. Nico siente cariño hacia ellos pero también rabia, y enfado, y algo que le da cosquillas y no sabe lo que es.Vallesordo es una novela entrañable con una voz original que nos habla de lo importante que es sentirse comprendido y vivir con ilusión. El brillante debut de un autor llamado a convertirse en uno de los escritores más interesantes de su generación.«Imposible no enamorarse de este niño muy fan de Fama, ¡a bailar! que nos cuenta su historia bailando (a falta de tacones) montado en unas latas de Coca Cola. Impresiona la aspereza de los adultos de su vida (de nuestra vida), pero pesan más la amistad, el primer amor y las ganas de vivir. Ternura, dolor y gritos de alegría para adentro: los secretos, los más intensos.» Berta García Faet.",
    price: 18.95,
    stock: 7,
    images: "images/vallesordo.jpg",
},

];