
const books = [
{
    id: 1,
    name: "La mala costumbre",
    author:"Alana S. Portero",
    description: "La mala costumbre es una versión bastarda y travesti del viajedel héroe: el viaje vital de una antiheroína trans en el que yonquis,divas del pop y ángeles caídos se unen para salvarla.",
    price: 19.00,
    stock: 10,
    images: "images/lamalacostumbre.jpg",
},
{
    id: 2,
    name: "El Power Ranger rosa",
    author:"Christo Casas",
    description: "Un joven español llega a Berlín en busca de trabajo. Por la noche pone copas en un bar marica y por el día intenta escribir la historia de su abuela, que también vivió en Alemania hace muchos años.",
    price: 14.00,
    stock: 2,
    images: "images/elpowerrangerrosa.jpg",
},
{
    id: 3,
    name: "Carcoma",
    author: "Layla Martínez",
    description: "Todas las casas guardan la historia de quienes las han habitado. Las paredes de esta casa perdida en el páramo hablan de voces que surgen de debajo de las camas.",
    price: 18.00,
    stock: 7,
    images: "images/carcoma.jpg",
},
{
    id: 4,
    name: "(h)amor amigas",
    author: "VVAA",
    description: "[La amistad] Consiste en amar a un ser humano como se querría amar atoda la humanidad».",
    price: 14.95,
    stock: 20,
    images: "images/amoramigas.jpg",
},
{
    id: 5,
    name: "Derecho a cita",
    author: "Roberta Marrero",
    description: "«Supongo que diré cualquier cosa que me aleje de la cárcel de mi propio corazón». Ha publicado novela gráfica, ensayo y poesía. Este es su segundo poemario.",
    price: 16.00,
    stock: 3,
    images: "images/derechoacita.jpg",
},
{
    id: 6,
    name: "Resistencia Bisexual",
    author: "Elisa Coll",
    description: "Una mirada potente y sin tapujos sobre la bisexualidad y la bifobia en primera persona. Un lugar de celebración, en un espacio habitable.",
    price: 15.00,
    stock: 7,
    images: "images/resistenciabisexual.jpg",
},
{
    id: 7,
    name: "La seducción",
    author: "Sara Torres",
    description: "Una joven fotógrafa se pone en contacto con una escritora veinte años mayor para tomarle unos retratos mientras trabaja en su próxima novela, titulada La seducción. Esa convivencia extraña en una casa. Una historia sobre el poder de las imágenes en el deseo y la potencia sanadora de la dulzura.",
    price: 18.90,
    stock: 9,
    images: "images/laseduccion.jpg",
},
{
    id: 8,
    name: "Contra el capacitismo",
    author: "Itxi Guerra",
    description: "El sistema capacitista es aquel que discrimina, violenta y asesina a las personas discapacitadas por el hecho de serlo. Surge del sistema capitalista al concebir a las personas según su capacidad de producción de beneficios a través de su fuerza de trabajo. Este fanzine busca relacionar esta opresión con el especismo, el patriarcado y el sistema carcelario.",
    price: 5.00,
    stock: 6,
    images: "images/laluchacontraelcapacitismo.jpg",
},
{
    id: 9,
    name: "Con esta Hoz",
    author: "Samuel Merino",
    description: "Con esta hoz es un libro que alberga varios libros en sí mismo y ofrece múltiples lecturas. Samuel Merino nos presenta un poema horizontal fragmentado por un ensayo poético. Al igual que la hoz es una herramienta para la siega de gramíneas, la escritura de Samuel se corta a sí misma y desprende sus espigas ofreciendo importantes floraciones.",
    price: 12.90,
    stock: 2,
    images: "images/conestahoz.jpg",
},
{
    id: 10,
    name: "A mordiscos la orquídea",
    author: "Joan Darós",
    description: "Cinco personajes pasan el verano alrededor de una piscina rosa. Uno de ellos no pertenece a la familia. Se trata del profesor de inglés que han contratado para no descuidar la educación de Júlia. Una niña, un profesor y tres adultos: Clara, Gisbert y Grau.",
    price: 14.00,
    stock: 3,
    images: "images/amordiscoslaorquidea.jpg",
},
{
    id: 11,
    name: "La rebelion de las hienas",
    author: "Mer Gómez",
    description: "Un viaje autobiográfico hacia el encuentro de referentes intersex para iniciar una revolución. Los relatos de sus protagonistas nos muestran la construcción de una identidad colectiva en la búsqueda de un presente/futuro de libertad y con derechos.",
    price: 16.00,
    stock: 11,
    images: "images/larebeliondelashienas.jpg",
},
{
    id: 12,
    name: "Alianzas rebeldes",
    author: "Clara Serra, Cristina Garaizábal, Laura Macaya",
    description: "Este libro es un ejercicio de libertad. Es una alianza rebelde entre distintas voces comprometidas con el valor la pluralidad y el disenso en el interior del feminismo. Frente a las falsas unidades impuestas, que siempre son excluyentes, y también contra el cinismo y la indiferencia, este proyecto asume que no hay uno sino muchos feminismos.",
    price: 17.00,
    stock: 3,
    images: "images/alianzasrebeldes.jpg",
},
{
    id: 13,
    name: "Nosotras vinimos tarde",
    author: "Elisa Coll",
    description: "Tras su reconocido ensayo Resistencia bisexual, Elisa Coll debuta en el campo de lo narrativo con Nosotras vinimos tarde, una novela valiente y rompedora en la que, a través de distintos géneros, hibrida ficción y memoria histórica, creando un caleidoscopio literario cargado de belleza, inteligencia y humor.",
    price: 18.00,
    stock: 7,
    images: "images/nosotrasvinimostarde.jpg",
},
{
    id: 14,
    name: "Panza de burro",
    author: "Andrea Abreu",
    description: "«Reconozco que al principio, cuando Panza de burro solo había crecido unos capitulitos, pensé que sería una novela sencilla y hermosa que abriría un hachazo en esa tela de invernadero que parecía ocultar un imaginario y un mundo que debían ser mostrados. Más adelante, la grandeza del libro, la inteligencia y el salvajismo de Andrea, su pulso poético y su falta total de miedo hicieron trizas la rafia>>Sabina Urraca.",
    price: 18.90,
    stock: 3,
    images: "images/panzadeburro.jpg",
},
{
    id: 15,
    name: "Los argonautas",
    author: "Maggue Nelson",
    description: "De una honestidad implacable, en esta memoria y a la vez ensayo, Maggie Nelson narra su singular y entrañable historia de amor con Harry Dogde, un artista transgénero, y cómo, en un contexto donde aún se debate la ley de unión civil entre homosexuales, intentan construir juntos una familia.En la tradición de intelectuales como Susan Sontag y Roland Barthes, Nelson entrelaza su propia experiencia con la teoría icónica, para explorar distintas construcciones culturales en torno a las nociones de identidad, sexualidad, género, maternidad y matrimonio.",
    price: 22.95,
    stock: 7,
    images: "images/losargonautas.jpg",
},
{
    id: 16,
    name: "Ese de anoche",
    author: "Alejandro Simón Partal",
    description: "La antología poética de Alejandro Simón Partal, uno de los autores más relevantes del momento.Esta primera antología de la poesía de Simón Partal es una gran fiesta, una esperada rave en la arena, junto a la orilla, muy cerca del mar y de sus profundidades.Ese de anoche recoge la aventura vital de un poeta que vive de cara a la vida: las sábanas tendidas en un prado abierto, un grupo de chicos que trabajan sus cuerpos en el paseo marítimo.",
    price: 18.90,
    stock: 1,
    images: "images/esedeanoche.jpg",
},
{
    id: 17,
    name: "Canto yo y la montaña baila",
    author: "Irene Solá",
    description: "Luego, Dolceta, que no puede parar de reír mientras cuenta las historias de las cuatro mujeres a las que colgaron por brujas. Un lugar, quizás, para empezar de nuevo y encontrar cierta redención.",
    price: 17.90,
    stock: 3,
    images: "images/cantoyolamontañabaila.jpg",
},
{
    id: 18,
    name: "Vallesordo",
    author: "Jonathan Arribas",
    description: "Una nueva y original voz de las letras españolas, una entrañable novela sobre una infancia en un pueblo de Zamora en la década de los dos mil.Nico es un niño que vive en un pueblo de Zamora. Juega a polis y cacos con los amigos, va en bici, pasa tiempo con su perra, La Yesi, se aburre y se divierte en el colegio, le duele la barriga, odia a los mastines del pastor, que le ladran sin parar, y le gusta mucho ensayar coreos.",
    price: 18.95,
    stock: 7,
    images: "images/vallesordo.jpg",
},

];